language: ruby
rvm:
  - 2.2
before_install:
  - npm install
  - pip install --user pillow
install: bundle install
script: npm run build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
    if [ "$TRAVIS_PULL_REQUEST" == "false" -o "$TRAVIS_BRANCH" == "dev" ]; then
        npm deploy
    fi
