language: ruby
rvm:
  - 2.2
before_install:
  - npm install
  - pip install --user pillow
install: bundle install
script: npm run build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
